# Generated by Django 4.0.4 on 2022-10-22 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_newtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoutineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('times', models.IntegerField()),
                ('done', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
