# Generated by Django 4.0.4 on 2022-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_newtask_user_routinetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetask',
            name='percent',
            field=models.IntegerField(null=True),
        ),
    ]
