# Generated by Django 4.0.4 on 2022-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_rename_done_routinetask_streakes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinetask',
            name='percent',
        ),
        migrations.AddField(
            model_name='routinetask',
            name='repetition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
