# Generated by Django 4.0.4 on 2022-10-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_routinetask_percent_routinetask_repetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetask',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
