# Generated by Django 4.0.4 on 2022-10-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_routinetask_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinetask',
            name='end_date',
        ),
    ]
