# Generated by Django 4.0.4 on 2022-10-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_routinetask_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinetask',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
