# Generated by Django 4.0.4 on 2022-10-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_routinetask_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetask',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
