# Generated by Django 4.0.4 on 2022-10-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_routinetask_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetask',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
