# Generated by Django 4.0.4 on 2022-10-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_routinetask_next_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newtask',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='routinetask',
            options={'ordering': ['-is_active', '-streakes']},
        ),
        migrations.AddField(
            model_name='newtask',
            name='is_routine',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
