# Generated by Django 4.0.4 on 2022-10-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_newtask_options_alter_routinetask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtask',
            name='routine_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
