# Generated by Django 4.0.4 on 2022-10-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_newtask_routine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetask',
            name='streakes_record',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
